### ISSUE TITLE
Could not load type 'Microsoft.ServiceFabric.Services.Remoting.RemotingListener' 

### ISSUE THREAD

**Issue by hanxinimm** [Microsoft/service-fabric-services-and-actors-dotnet#141]
System.TypeInitializationException: The type initializer for 'Security.ActorModel.RegisterActor' threw an exception. ---> System.TypeLoadException: Could not load type 'Microsoft.ServiceFabric.Services.Remoting.RemotingListener' from assembly 'Microsoft.ServiceFabric.Services.Remoting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Reflection.CustomAttribute._GetPropertyOrFieldData(RuntimeModule pModule, Byte** ppBlobStart, Byte* pBlobEnd, String& name, Boolean& bIsProperty, RuntimeType& type, Object& value)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
   at Microsoft.ServiceFabric.Actors.Remoting.ActorRemotingProviderAttribute.GetProvider(IEnumerable`1 types)
   at Microsoft.ServiceFabric.Actors.Client.ActorProxyFactory.GetOrSetProxyFactory(Type actorInterfaceType)
   at Microsoft.ServiceFabric.Actors.Client.ActorProxyFactory.CreateActorProxy[TActorInterface](Uri serviceUri, ActorId actorId, String listenerName)
   at Microsoft.ServiceFabric.Actors.Client.ActorProxy.Create[TActorInterface](ActorId actorId, Uri serviceUri, String listenerName)
   at Security.ActorModel.RegisterActor..cctor() in D:\LotteryCloud\SecurityCenter\Command\Server\Security.ActorModel\Actors\RegisterActor.cs:line 38
   --- End of inner exception stack trace ---
   at Security.ActorModel.RegisterActor..ctor(ActorService actorService, ActorId actorId, Repository`2 repository, IDistributedCache distributedCache) in D:\LotteryCloud\SecurityCenter\Command\Server\Security.ActorModel\Actors\RegisterActor.cs:line 47
   at Security.ActorModel.Program.<>c__DisplayClass0_0.<Main>b__2(ActorService actorService, ActorId actorId) in D:\LotteryCloud\SecurityCenter\Command\Server\Security.ActorModel\Program.cs:line 50
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.GetOrCreateActor(ActorId actorId, Boolean timerUse, Boolean createDummyActor)
   at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.DispatchToActorAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Boolean createIfRequired, Func`3 actorFunc, String callContext, Boolean timerCall, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Remoting.Runtime.ServiceRemotingCancellationHelper.DispatchRequest[T](Int32 interfaceId, Int32 methodId, String callContext, Func`2 dispatchFunc)
   at Microsoft.ServiceFabric.Actors.Remoting.V2.Runtime.ActorServiceRemotingDispatcher.HandleActorMethodDispatchAsync(IActorRemotingMessageHeaders messageHeaders, IServiceRemotingRequestMessageBody msgBody)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportMessageHandler.RequestResponseAsync(FabricTransportRequestContext requestContext, FabricTransportMessage fabricTransportMessage)

Microsoft.ServiceFabric 6.3.162
Microsoft.ServiceFabric.Actors  3.2.162

the latest source code work better,what about when to release the latest version
the version 6.3.162 Remoting V2 can't work

**Comment by davebally** [comment]
Having the same problem,  Service that connection to another service works fine under "Microsoft.ServiceFabric.Services.Remoting" Version="3.1.301"
Upgrade to 3.2.162 and get 
"Message="Could not load type 'Microsoft.ServiceFabric.Services.Remoting.RemotingListener' from assembly 'Mic..."
"

**Comment by amanbha** [comment]
@hanxinimm Which library has the type Security.ActorModel.RegisterActo, Is this also rebuilt with 3.2.162 version of Microsfot.ServiceFabric.Services.Remoting

@davebally  Could you also please share the call stack, is the code also using another library which uses 
Microsfot.ServiceFabric.Services.Remoting like in the case of @hanxinimm

**Comment by davebally** [comment]
@amanbha 

Yes, we are using another library presently built with 3.1.301. Upgrading both service ( the RPC clientr ) and library to 3.2.162 has same effect 

`Could not load type 'Microsoft.ServiceFabric.Services.Remoting.RemotingListener' from assembly 'Microsoft.ServiceFabric.Services.Remoting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
`

Stack trace ;

`  at System.Reflection.CustomAttribute._GetPropertyOrFieldData(RuntimeModule pModule, Byte** ppBlobStart, Byte* pBlobEnd, String& name, Boolean& bIsProperty, RuntimeType& type, Object& value)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
   at Microsoft.ServiceFabric.Services.Remoting.ServiceRemotingProviderAttribute.GetProvider(IEnumerable 1 types)
   at Microsoft.ServiceFabric.Services.Remoting.Client.ServiceProxyFactory.CreateServiceProxy[TServiceInterface](Uri serviceUri, ServicePartitionKey partitionKey, TargetReplicaSelector targetReplicaSelector, String listenerName)
   at WP.HCG.Lib.ServiceFabricHelpers.CryptService.CryptService.<Encrypt>d__2.MoveNext() in C:\Users\daveb\source\repos\gbl.helper\WP.HCG.Lib.ServiceFabricHelpers\CryptService\CryptService.cs:line 69`

**Comment by amanbha** [comment]
@davebally Looks like you are using Reflection to find it. The type has been renamed to allow for fixing of Serialization related issues in V2 remoting stack, if it wasn't for Reflection, it would have been a compile time error. Its renamed to RemotingListenerVersion. 
Please see: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-use-remoting-v2interfacecompatible-stack

**Comment by davebally** [comment]
@amanbha Erm..   Im not using reflection,  im just using Microsoft.ServiceFabric.Services.Remoting.Client.ServiceProxyFactory.CreateServiceProxy that calls Microsoft.ServiceFabric.Services.Remoting.ServiceRemotingProviderAttribute.GetProvider which uses reflection...  Or am i missing something ?!?

**Comment by amanbha** [comment]
@davebally  oh ok, got it, sorry, I misread the stack. Looks like some mismatch somewhere. Could you please check how are you specifying the FabricTransportServiceRemotingProvider for your RemotingInterface.

**Comment by davebally** [comment]
@amanbha Ah, the interface is defined in the library.  Not sure how but after upgrading it wasnt fully recompiling , after a clean then there were compile errors on :
`[assembly: FabricTransportServiceRemotingProvider(RemotingListener = RemotingListener.V2Listener, RemotingClient = RemotingClient.V2Client)]`
which needed changing to :
`[assembly: FabricTransportServiceRemotingProvider(RemotingClientVersion = RemotingClientVersion.V2,RemotingListenerVersion = RemotingListenerVersion.V2)]`

Looks like the incompatibility is being caused by a drift in versions between library and client.
Seems like we are going to have to be careful with this in future.....

**Comment by amanbha** [comment]
@davebally, glad its working now for you. Yes, RemotingListener, RemotingClient  have been replaced by RemotingListenerVersion, and RemotingClientVersion to allow for fixing of some serialization issues in V2 remoting stack.

**Comment by hanxinimm** [comment]
@amanbha 

it doesn't work for me.

 my code:

![image](https://user-images.githubusercontent.com/13499426/43112164-3c529108-8f27-11e8-9b95-eeca39f255bb.png)
![image](https://user-images.githubusercontent.com/13499426/43112169-4a8a1282-8f27-11e8-91de-55d08485138f.png)
![image](https://user-images.githubusercontent.com/13499426/43112175-597d11cc-8f27-11e8-9501-947bdc85cbcc.png)
![image](https://user-images.githubusercontent.com/13499426/43112197-749fadac-8f27-11e8-82fc-44d450deecb6.png)

What did I miss？

**Comment by amanbha** [comment]
@hanxinimm  Could you share code snippet where is Security.ActorModel.RegisterActor defined and if its compiled with latest version of nuget package?

**Comment by hanxinimm** [comment]
I found the reason,
![image](https://user-images.githubusercontent.com/13499426/43128692-33eef720-8f65-11e8-8943-e7f57e0c3cd8.png)
the IIDCreatorActor interface is old version
I forgot to upgrade it

**Comment by amanbha** [comment]
@hanxinimm  Glad to know its working for you, will close this issue.
