### ISSUE TITLE
Building Actor projects fails with dotnet core 3 preview 7

### ISSUE THREAD

**Issue by aL3891** [microsoft/service-fabric-services-and-actors-dotnet#216]
**Describe the bug**
Building an actor service projects fails during service manifest generation

**To Reproduce**
In VS 16.3 preview 1, Create a new Service fabric application with a .net core actor service, build.

**Expected behavior**
Build is succesful

**Additional context**
Build fails with the following error 

```
error MSB3073: The command "dotnet "obj\\FabActUtilTemp\FabActUtil.dll" /spp:"PackageRoot" /t:manifest /sp:"Actor1" /in:"bin\Debug\netcoreapp3.0\win7-x64\\Actor1.dll" /arp:"C:\Users\Allan\source\repos\Application7\Actor1\bin\Debug\netcoreapp3.0\win7-x64\\" /smep:Exe " exited with code -2147450730.
```

manually running the command gives the following result

```dotnet "obj\\FabActUtilTemp\FabActUtil.dll" /spp:"PackageRoot" /t:manifest /sp:"Actor1" /in:"bin\Debug\netcoreapp3.0\win7-x64\\Actor1.dll" /arp:"C:\Users\Allan\source\repos\Application7\Actor1\bin\Debug\netcoreapp3.0\win7-x64\\" /smep:Exe
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - The following frameworks were found:
      2.1.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.0-preview3-27014-02 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.0.0-preview6-27804-01 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.0.0-preview7-27912-14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download```

**Comment by dbreshears** [comment]
Thanks!   We have a bug on this we were discussing today.,   it still occurs in Preview 8 when calling FabActUtil from the tooling.  Will investigate

2>------ Rebuild All started: Project: Actor1, Configuration: Debug Any CPU ------
2>Actor1 -> C:\Users\devinb\source\repos\Application41\Actor1\bin\Debug\netcoreapp3.0\win7-x64\Actor1.dll
2>EXEC : error :
2>  An assembly specified in the application dependencies manifest (FabActUtil.deps.json) was not found:
2>    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '3.0.0-preview8-28373-17'
2>    path: 'SOS_README.md'

**Comment by oising** [comment]
I'm having a similar failure with the SF SDK (latest version as of today)  -- I'm not sure if it's the same, but I don't want to add a dupe if it is. I'm using net core 3 preview 7, and while the actor and interface projects build, the SF project blows up with `The "GetServiceProjectReferences" task failed unexpectedly` and the call stack looks like this:

```
error MSB4018: The "GetServiceProjectReferences" task failed unexpectedly.
error MSB4018: System.ArgumentNullException: Value cannot be null.
error MSB4018: Parameter name: source
error MSB4018:    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
error MSB4018:    at Microsoft.VisualStudio.Azure.Fabric.BuildTasks.ServiceModelServiceSlim.GetPrimaryCodePackage(ServiceManifestSlim serviceManifest)
error MSB4018:    at Microsoft.VisualStudio.Azure.Fabric.BuildTasks.GetServiceProjectReferences.SetMetadataForProjectReferences(PackageBehaviorOptions packageBehavior)
error MSB4018:    at Microsoft.VisualStudio.Azure.Fabric.BuildTasks.GetServiceProjectReferences.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

I then shelled out and ran `dotnet restore` and `dotnet build` and got something a bit more specific:

```
PS> dotnet --version
3.0.100-preview7-012821
PS> dotnet build
Microsoft (R) Build Engine version 16.3.0-preview-19329-01+d31fdbf01 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 30.13 ms for C:\projects\logient\src\hqhilo\demo1\ClientActors\ActorThermostatClient\ActorThermostatClient.csproj.
  Restore completed in 30.13 ms for C:\projects\logient\src\hqhilo\demo1\ClientActors\ActorThermostatClient.Interfaces\ActorThermostatClient.Interfaces.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  ActorThermostatClient.Interfaces -> C:\projects\logient\src\hqhilo\demo1\ClientActors\ActorThermostatClient.Interfaces\bin\Debug\netcoreapp3.0\win7-x64\ActorThermostatClient.Interfaces.dll
  ActorThermostatClient -> C:\projects\logient\src\hqhilo\demo1\ClientActors\ActorThermostatClient\bin\Debug\netcoreapp3.0\win7-x64\ActorThermostatClient.dll
EXEC : error :  [C:\projects\logient\src\hqhilo\demo1\ClientActors\ActorThermostatClient\ActorThermostatClient.csproj]
    An assembly specified in the application dependencies manifest (FabActUtil.deps.json) was not found:
      package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '3.0.0-preview7-27912-14'
      path: 'SOS_README.md'
C:\Users\oisin.DESKTOP-1HQA4NP\.nuget\packages\microsoft.servicefabric.actors\3.4.658\build\netcoreapp2.0\Microsoft.ServiceFabric.Actors.targets(27,5): error MSB3073: The command "dotnet "obj\\FabActUtilTemp\FabActUtil.dll" /spp:"PackageRoot" /t:manifest /sp:"ActorThermostatClient" /in:"bin\Debug\netcoreapp3.0\win7-x64\\ActorThermostatClient.dll" /arp:"C:\projects\logient\src\hqhilo\demo1\ClientActors\ActorThermostatClient\bin\Debug\netcoreapp3.0\win7-x64\\" /smep:Exe " exited with code -2147450740. [C:\projects\logient\src\hqhilo\demo1\ClientActors\ActorThermostatClient\ActorThermostatClient.csproj]

Build FAILED.

EXEC : error :  [C:\projects\logient\src\hqhilo\demo1\ClientActors\ActorThermostatClient\ActorThermostatClient.csproj]
C:\Users\oisin.DESKTOP-1HQA4NP\.nuget\packages\microsoft.servicefabric.actors\3.4.658\build\netcoreapp2.0\Microsoft.ServiceFabric.Actors.targets(27,5): error MSB3073: The command "dotnet "obj\\FabActUtilTemp\FabActUtil.dll" /spp:"PackageRoot" /t:manifest /sp:"ActorThermostatClient" /in:"bin\Debug\netcoreapp3.0\win7-x64\\ActorThermostatClient.dll" /arp:"C:\projects\logient\src\hqhilo\demo1\ClientActors\ActorThermostatClient\bin\Debug\netcoreapp3.0\win7-x64\\" /smep:Exe " exited with code -2147450740. [C:\projects\logient\src\hqhilo\demo1\ClientActors\ActorThermostatClient\ActorThermostatClient.csproj]
    0 Warning(s)
    2 Error(s)
```

I'm using VS 2019 16.3-preview1 here, just to get the latest and greatest for netcore3 (which has a go-live license now, afaik)

Is this related, or should I open a new issue?

**Comment by oising** [comment]
The fix got checked in and it works. See my comment on the commit: https://github.com/oising/service-fabric-services-and-actors-dotnet/commit/dc86d3ae8abb99b56db4bf8f903703a8fe6af533

**Comment by aL3891** [comment]
Great, thanks! should i close or will you do that when you merge? :)

**Comment by amanbha** [comment]
@aL3891 The PR is merged, will close it once a nuget package is out with the fix.

**Comment by amanbha** [comment]
Fix available in Microsoft.ServiceFabric.Actors nuget package version >= 3.4.644

**Comment by MarkDeVerno** [comment]
@amanbha This is still an issue if you attempt to create a package when you publish.  For example:

`dotnet publish MyProj.sfproj -c Release -p:PublishSingleFile=true -r win7-x64 --self-contained=false -t:Package`

Is there a workaround?

**Comment by amanbha** [comment]
@anantshankar17 @dbreshears  could you please see if it's supposed to work with publish?

**Comment by MarkDeVerno** [comment]
@amanbha I found a similar issue #194.  The workaround addresses my issue.

**Comment by vitaliiTolmachov** [comment]
This issue might take place if U have optional parameter in your Actor
`The actor interface methods must not have out, ref or optional parameters. (Parameter 'actorInterfaceType')`

**Comment by tom-gough** [comment]
> Fix available in Microsoft.ServiceFabric.Actors nuget package version >= 3.4.644

For anyone googling this issue, this appears to be a typo, and 3.4.664 is the version you need.
