### ISSUE TITLE
No transactions in WCF service hosted by WcfCommunicationListener

### ISSUE THREAD

**Issue by dronkoff** [Microsoft/service-fabric-services-and-actors-dotnet#67]
I have a contract and implementation
```CSharp
    [ServiceContract(Namespace = "http://TestInterfaces.org")]
    public interface ICalculator
    {
        [OperationContract]
        [TransactionFlow(TransactionFlowOption.Allowed)]
        string GetTransactionInfo();
    }
//..........
    public class CalcService : ICalculator
    {
        [OperationBehavior(TransactionScopeRequired = true, TransactionAutoComplete = true)]
        public string GetTransactionInfo()
        {
            Console.WriteLine("Received GetTransactionInfo");
            var res = "No transaction context found";
            if(Transaction.Current != null)
            {
                res = $"LocalID: {Transaction.Current.TransactionInformation.LocalIdentifier}\n";
                res += $"DistributedID: {Transaction.Current.TransactionInformation.DistributedIdentifier}\n";
                res += $"IsolationLevel: {Transaction.Current.IsolationLevel}\n";
                res += $"CreationTime: {Transaction.Current.TransactionInformation.CreationTime}, Status: {Transaction.Current.TransactionInformation.Status}";
            }
            Console.WriteLine("Return: {0}", res);
            return res;
        }
    }

```

They are packaged as stateless service

```CSharp
    internal sealed class CalcSvc : StatelessService
    {
        public CalcSvc(StatelessServiceContext context)
            : base(context)
        { }

        protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            const int bufferSize = 512000; //500KB
            NetTcpBinding binding = new NetTcpBinding(SecurityMode.None)
            {
                SendTimeout = TimeSpan.FromSeconds(30),
                ReceiveTimeout = TimeSpan.FromSeconds(30),
                CloseTimeout = TimeSpan.FromSeconds(30),
                MaxConnections = 1000,
                MaxReceivedMessageSize = bufferSize,
                MaxBufferSize = bufferSize,
                MaxBufferPoolSize = bufferSize * Environment.ProcessorCount,
                TransactionFlow = true
            };

            ServiceInstanceListener listener = new ServiceInstanceListener(context =>
                {
                    var wcfListener = new WcfCommunicationListener<TestInterfaces.ICalculator>(
                        context, new TestImpl.CalcService(), binding, "CalcServiceEndpoint");

                    var behaviorBehavior = wcfListener.ServiceHost.Description.Behaviors.Find<ServiceBehaviorAttribute>();
                    //behaviorBehavior.ConcurrencyMode = ConcurrencyMode.Single;
                    //behaviorBehavior.InstanceContextMode = InstanceContextMode.PerSession;
                    wcfListener.ServiceHost.Description.Behaviors.Remove<ServiceDebugBehavior>();
                    wcfListener.ServiceHost.Description.Behaviors.Add(new ServiceDebugBehavior() { IncludeExceptionDetailInFaults = true} );
                    return wcfListener;
                }
            );
            return new[] { listener };
        }
        protected override async Task RunAsync(CancellationToken cancellationToken)
        {
            long iterations = 0;
            while (true)
            {
                cancellationToken.ThrowIfCancellationRequested();
                ServiceEventSource.Current.ServiceMessage(this.Context, "Working-{0}", ++iterations);
                await Task.Delay(TimeSpan.FromSeconds(1), cancellationToken);
            }
        }
    }

```

Endpoint in service manifest

```xml
  <Resources>
    <Endpoints>
      <Endpoint Name="CalcServiceEndpoint" Protocol="tcp"  Port="12348" />
    </Endpoints>
  </Resources>
```

Client calls service using this code

```csharp
    public class CalcSfClient : ServicePartitionClient<WcfCommunicationClient<ICalculator>>
    {
        public CalcSfClient(
            ICommunicationClientFactory<WcfCommunicationClient<ICalculator>> communicationClientFactory, 
            Uri serviceUri, 
            ServicePartitionKey partitionKey = null, 
            TargetReplicaSelector targetReplicaSelector = TargetReplicaSelector.Default, 
            string listenerName = null, 
            OperationRetrySettings retrySettings = null)
           : base(communicationClientFactory, serviceUri, partitionKey, targetReplicaSelector, listenerName, retrySettings)
        {
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("go");
            var sfServiceUri = new Uri("fabric:/TestSFApp/CalcSvc");
            //var sfServiceUri = new Uri("fabric:/TestSFApp/CalcConsoleSvc");
            const int bufferSize = 512000; //500KB
            NetTcpBinding binding = new NetTcpBinding(SecurityMode.None)
            {
                SendTimeout = TimeSpan.FromSeconds(30),
                ReceiveTimeout = TimeSpan.FromSeconds(30),
                CloseTimeout = TimeSpan.FromSeconds(30),
                MaxConnections = 1000,
                MaxReceivedMessageSize = bufferSize,
                MaxBufferSize = bufferSize,
                MaxBufferPoolSize = bufferSize * Environment.ProcessorCount,
                TransactionFlow = true
            };

            try
            {
                var sfFactory = new WcfCommunicationClientFactory<ICalculator>(
                    clientBinding: binding,
                    servicePartitionResolver: ServicePartitionResolver.GetDefault());
                var sfClient = new CalcSfClient(sfFactory, sfServiceUri);

                while (true)
                {
                    Console.WriteLine("\nPress Enter for GetTran, Esc for exit: \n");
                    var key = Console.ReadKey(true);
                    if(key.Key == ConsoleKey.Escape)
                    {
                        break;
                    }
                    if(key.Key == ConsoleKey.Enter)
                    {
                        using (var tran = new TransactionScope())
                        {
                            Console.WriteLine(sfClient.InvokeWithRetry(client => client.Channel.GetTransactionInfo()));
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }
    }  
```  

I successfully publish it into local cluster (1 Node) and call. 
And here a problem occurs.
### Expected behavior
Inside GetTransactionInfo() implementation Transaction.Current is not null and Transaction.Current.TransactionInformation.DistributedIdentifier is not Guid.Empty.

### Current behavior
Transaction.Current is null inside GetTransactionInfo() method.

What's interesting, if I publish exactly the same code as guest executable, where I will create ServiceHost manually, the transaction flow will work as expected.

**Comment by VipulM-MSFT** [comment]
@dronkoff - the WCF communication listener may not work with all of the functionality as they may require specific binding and right settings. It is possible that the base type might be rewriting some of the service behavior. If you debug and find the issue that can be fixed in a generic way, please feel free to submit the PR.

**Comment by dronkoff** [comment]
Imho, this issue is something not directly related to binding because if something wrong with binding we won't see a transaction flow, so distributed transaction won't come from the client, but there should be a local transaction as the [OperationBehavior(TransactionScopeRequired = true)] attribute is specified.
So, with working distributed transaction flow inside operation we'll have:
```csharp
Transaction.Current == transaction instance
Transaction.Current.TransactionInformation.LocalIdentifier == local transaction guid
Transaction.Current.TransactionInformation.DistributedIdentifier == distributed transaction guid
```
If something is wrong in bindings and transaction flow doesn't work, we'll have:
```csharp
Transaction.Current == transaction instance
Transaction.Current.TransactionInformation.LocalIdentifier == local transaction guid
Transaction.Current.TransactionInformation.DistributedIdentifier == Guid.Empty
```
And in this case we have
```csharp
Transaction.Current == null
```

**Comment by suchiagicha** [comment]
Because  of no communication , am closing this issue. Feel free to open it if you are still seeing this issue.

**Comment by dronkoff** [comment]
Why did you close it? 
Do WcfCommunicationListener now supports transaction?

**Comment by Jaans** [comment]
I'm seeing the same behaviour with SF v6.4.

I also set the `TransactionIsolationLevel` of the `ServiceBehavior` attribute for the Service:
```
[ServiceBehavior( TransactionIsolationLevel = IsolationLevel.ReadCommitted )]
public class MyService : IMyService
{
    [OperationBehavior( TransactionScopeRequired = true )]
    public Task<Domain.MyData> GetDataAsync( Guid identifier )
    {
        ...
    }    
}
```

Not only do transaction not work, but when I have the transaction isolation attribute set, the WCF listener fails with the following error message, despite the class being like above and otherwise working just fine when hosted as WCF service via IIS.
```
System.RA' reported Warning for property 'ReplicaOpenStatus'.
Replica had multiple failures during open on _Node_1. API call: IStatelessServiceInstance.Open(); Error = System.InvalidOperationException (-2146233079)
The service 'MyService' is configured with a TransactionIsolationLevel but no operations are configured with TransactionScopeRequired set to true. TransactionIsolationLevel requires at least one operation with TransactionScopeRequired set to true.
   at System.ServiceModel.Dispatcher.TransactionValidationBehavior.ValidateServiceBehaviorAttributeWithNoScopeRequired(ServiceDescription service)
   at System.ServiceModel.Dispatcher.TransactionValidationBehavior.System.ServiceModel.Description.IServiceBehavior.Validate(ServiceDescription service, ServiceHostBase serviceHostBase)
   at System.ServiceModel.Description.DispatcherBuilder.ValidateDescription(ServiceDescription description, ServiceHostBase serviceHost)
   at System.ServiceModel.Description.DispatcherBuilder.InitializeServiceHost(ServiceDescription description, ServiceHostBase serviceHost)
   at System.ServiceModel.ServiceHostBase.InitializeRuntime()
   at System.ServiceModel.ServiceHostBase.OnBeginOpen(TimeSpan timeout, AsyncCallback callback, Object state)
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncResult.InvokeOpen()
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncResult..ctor(CommunicationObject communicationObject, TimeSpan timeout, AsyncCallback callback, Object state)
   at System.ServiceModel.Channels.CommunicationObject.BeginOpen(TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceFabric.Services.Communication.Wcf.Runtime.WcfCommunicationListener`1.Microsoft.ServiceFabric.Services.Communication.Runtime.ICommunicationListener.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__13.MoveNext()
For more information see: https://aka.ms/sfhealth
```
